config/routes.rb
HackerUnion::Application.routes.draw do

  devise_for :members, :controllers => {:omniauth_callbacks => 'members/omniauth_callbacks'}

  root :to => "home#index"

  resources :members do
    member do
      put :approve
      put :toggle_ambassador
      put :toggle_admin
      get :edit_profile
    end
    collection do
      get :pending
    end
  end

  [:events, :announcements].each do |thing|
    resources thing do
      member do
        put :approve
      end
      collection do
        get :pending
      end
    end
  end

end

app/models/announcement.rb
class Announcement < ActiveRecord::Base
  belongs_to :member

  scope :approved, where(approved: true)
  scope :not_approved, where(approved: false)
  scope :latest, lambda { |count|
    approved.order('created_at desc').limit(count)
  }

  def approve!
    self.approved = true
    save!
  end
  
end

app/controllers/announcements_controller.rb
class AnnouncementsController < ApplicationController
  before_filter :authenticate_member!, :only => [:new, :create]
  respond_to :html

  load_and_authorize_resource

  def index
    @announcements = Announcement.approved

    respond_with @announcements
  end

  def show
    @announcement = Announcement.find(params[:id])

    respond_with @announcement
  end

  def new
    @announcement = Announcement.new
    respond_with @announcement
  end

  def edit
    @announcement = Announcement.find(params[:id])
  end

  def create
    @announcement = Announcement.new(params[:announcement])
    @announcement.approved = false
    @announcement.member = current_member

    if @announcement.save
      redirect_to @announcement, notice: 'Announcement was successfully created.'
    else
      render action: "new"
    end
  end

  def update
    @announcement = Announcement.find(params[:id])

    if @announcement.update_attributes(params[:announcement])
      redirect_to @announcement, notice: 'Announcement was successfully updated.'
    else
      render action: "edit"
    end
  end

  def destroy
    @announcement = Announcement.find(params[:id])
    @announcement.destroy
    redirect_to announcements_url
  end

  def pending
    @announcements = Announcement.not_approved
    respond_with @announcements
  end

  def approve
    @announcement = Announcement.find(params[:id])
    @announcement.approve!
    redirect_to pending_announcements_path
  end
end

app/views/announcements/_form.html.haml
= form_for @announcement, :html => { class: 'form-horizontal' } do |f|
  .errors=f.error_messages
  .control-group
    = f.label :title, class: 'control-label'
    .controls
      = f.text_field :title, class: 'text_field'
  .control-group
    = f.label :text, class: 'control-label'
    .controls
      = f.text_area :text, class: 'text_field'
  .form-actions
    = f.submit nil, class: 'btn btn-primary'
    = link_to t('.cancel', :default => t("helpers.links.cancel")), announcements_path, class: 'btn'

app/views/announcements/_list.html.haml
%table.table.table-striped
  %thead
    %tr
      %th= model_class.human_attribute_name(:title)
      %th= model_class.human_attribute_name(:text)
      %th= model_class.human_attribute_name(:created_at)
      %th= model_class.human_attribute_name(:creator)
      %th=t '.actions', :default => t("helpers.actions")
  %tbody
    - @announcements.each do |announcement|
      %tr
        %td= link_to announcement.title, announcement_path(announcement)
        %td= announcement.text
        %td= announcement.created_at
        %td= link_to announcement.member.email, member_path(announcement.member)
        %td= action_buttons(announcement)

= link_to t('.new', :default => t("helpers.links.new")), new_announcement_path, class: 'btn btn-primary'

app/views/announcements/edit.html.haml
- model_class = @announcement.class
%h1=t '.title', default: t('helpers.titles.edit', model: model_class.model_name.human, default: "Edit #{model_class.model_name.human}")
= render partial: 'form'

app/views/announcements/index.html.haml
- model_class = Announcement
%h1=t '.title', :default => model_class.model_name.human.pluralize

=render partial: 'list', locals: {model_class: model_class}

app/views/announcements/new.html.haml
- model_class = @announcement.class
%h1=t '.title', :default => t('helpers.titles.new', :model => model_class.model_name.human, :default => "New #{model_class.model_name.human}")

= render :partial => 'form'

app/views/announcements/pending.html.haml
- model_class = Announcement
%h1=t '.pending-title', :default => 'Pending ' + model_class.model_name.human.pluralize

=render partial: 'list', locals: {model_class: model_class}

app/views/announcements/show.html.haml
- model_class = @announcement.class
%h1=t '.title', :default => model_class.model_name.human

%p
  %strong= model_class.human_attribute_name(:title) + ':'
  %br
  = @announcement.title
%p
  %strong= model_class.human_attribute_name(:text) + ':'
  %br
  = @announcement.text
%p
  %strong= model_class.human_attribute_name(:created_at) + ':'
  %br
  = @announcement.created_at
%p
  %strong= model_class.human_attribute_name(:approved) + ':'
  %br
  = @announcement.approved
%p
  %strong= model_class.human_attribute_name(:member) + ':'
  %br
  = link_to @announcement.member.email, member_path(@announcement.member)

.form-actions
  = link_to t('.back', :default => t("helpers.links.back")), announcement_path, class: 'btn'
  = link_to t('.edit', :default => t("helpers.links.edit")), edit_announcement_path(@announcement), class: 'btn'
  = link_to t('.destroy', :default => t("helpers.links.destroy")), announcement_path(@announcement), :method => "delete", :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')), class: 'btn btn-danger'