config/routes.rb
HackerUnion::Application.routes.draw do

  devise_for :members, :controllers => {:omniauth_callbacks => 'members/omniauth_callbacks'}

  root :to => "home#index"

  resources :members do
    member do
      put :approve
      put :toggle_ambassador
      put :toggle_admin
      get :edit_profile
    end
    collection do
      get :pending
    end
  end

  [:events, :announcements].each do |thing|
    resources thing do
      member do
        put :approve
      end
      collection do
        get :pending
      end
    end
  end

end

app/views/layouts/_navbar.html.haml
.navbar.navbar-fixed-top
  .navbar-inner
    .container-fluid
      %a.btn.btn-navbar(data-target=".nav-collapse" data-toggle="collapse")
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      %a.brand(href=root_path) Hacker Union
      .container.nav-collapse
        %ul.nav
          %li= login_or_logout_link
          %li= sign_up_or_edit_registration_link
          %li= edit_profile_link

app/views/layouts/_sidebar.html.haml
-if !current_member
  .well.sidebar-nav{style: "visibility: hidden;"}
-else
  .well.sidebar-nav
    - if current_member && current_member.admin?
      %ul.nav.nav-list
        %li.nav-header Admin navigation
        %li=link_to('Pending Members', pending_members_path)
        %li=link_to('Pending Events', pending_events_path)
        %li=link_to('Pending Announcements', pending_announcements_path)
      %br
    - if current_member
      %ul.nav.nav-list
        %li.nav-header Navigate
        %li=link_to 'Members', members_path
        %li=link_to 'Events', events_path
        %li=link_to 'Announcements', announcements_path

app/views/layouts/application.html.haml
!!! 5
%html(lang="en")
  %head
    %meta(charset="utf-8")
    %meta(name="viewport" content="width=device-width, initial-scale=1.0")
    %title= content_for?(:title) ? yield(:title) : "Hacker Union"
    = javascript_include_tag "application"
    = csrf_meta_tags
    / Le HTML5 shim, for IE6-8 support of HTML elements
    /[if lt IE 9]
      = javascript_include_tag "http://html5shim.googlecode.com/svn/trunk/html5.js"
    = stylesheet_link_tag "application", :media => "all"
    %link(href="/favicon.ico" rel="shortcut icon")
    %link(href="images/apple-touch-icon.png" rel="apple-touch-icon")
    %link(href="images/apple-touch-icon-72x72.png" rel="apple-touch-icon" sizes="72x72")
    %link(href="images/apple-touch-icon-114x114.png" rel="apple-touch-icon" sizes="114x114")

  %body
    =render 'layouts/navbar'

    .container-fluid
      .row-fluid
        .span3
          =render 'layouts/sidebar'
        .span9
          -if alert
            %p.alert.alert-info= alert
          = yield

      %footer
        %p &copy; Hacker Union 2012
        %p Have feedback on the site? Want to change something? #{open_issue}, #{fork_us_on_github} or send an email to Brandon!
    /
      Javascripts
      \==================================================
    / Placed at the end of the document so the pages load faster

app/views/layouts/launch.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html>
    <head>
        <title>Hacker Union - Apply for the Hacker Union</title>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
        
		<%= stylesheet_link_tag "application", :media => "all" %>     		
		
		<%= javascript_include_tag "application" %>
        <%= stylesheet_link_tag "launch" %>
        <%= javascript_include_tag "jquery.easing.1.3" %>
    </head>

    <body>   
      <%= yield %>
    </body>
</html>