config/routes.rb
HackerUnion::Application.routes.draw do

  devise_for :members, :controllers => {:omniauth_callbacks => 'members/omniauth_callbacks'}

  root :to => "home#index"

  resources :members do
    member do
      put :approve
      put :toggle_ambassador
      put :toggle_admin
      get :edit_profile
    end
    collection do
      get :pending
    end
  end

  [:events, :announcements].each do |thing|
    resources thing do
      member do
        put :approve
      end
      collection do
        get :pending
      end
    end
  end

end

app/models/member.rb
class Member < ActiveRecord::Base

  devise :database_authenticatable,
         :registerable, :recoverable,
         :rememberable, :trackable,
         :validatable, :omniauthable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation,
                  :remember_me, :name, :approved, :admin, :whyhacker, :city

  has_and_belongs_to_many :affiliations

  has_and_belongs_to_many :skills
  has_many :events

  ransackable_associations :affiliations
  ransackable_associations :skills

  def approve!
    self.approved = true
    save!
  end

  def self.find_for_github_oauth(access_token, signed_in_resource=nil)
    data = access_token['info']
    if member = Member.where(:email => data["email"]).first
      member
    else
      Member.create!(:email => data["email"], :password => Devise.friendly_token[0,20], :name => data["name"])
    end
  end

end

app/controllers/members/omniauth_callbacks_controller.rb
class Members::OmniauthCallbacksController < Devise::OmniauthCallbacksController

  def github
    @member = Member.find_for_github_oauth(request.env["omniauth.auth"], current_member)
    return render_403 if @member.nil?

    if @member.persisted?
      flash[:notice] = I18n.t "devise.omniauth_callbacks.success", :kind => "Github"
      sign_in_and_redirect @member, :event => :authentication
    else
      session["devise.github_data"] = request.env["omniauth.auth"]
      redirect_to new_member_registration_url
    end
  end
end

app/controllers/members_controller.rb
class MembersController < ApplicationController
  before_filter :authenticate_member!, :only => [:index]

  load_and_authorize_resource

  def index
    @q = Member.search params[:q]
    if params[:ambassador] == '0' # Find out if checkbox is checked
      @q = @q.result.search(ambassador_eq: true)
    end
    @members = @q.result(distinct: true).where(approved: true)
  end

  def pending
    @members = Member.where(approved: false)
  end

  def approve
    @member = Member.find(params[:id])
    @member.approve!
    redirect_to pending_members_path, alert: "'#{@member.name}' successfully approved"
  end

  def show
    @member = Member.find params[:id]
  end

  def edit_profile
    @member = Member.find params[:id]
  end

  def update
    @member = Member.find params[:id]

    @member.name = params[:name]

    parse_affiliation_list(params[:affiliations]).each do |a|
      affiliation = Affiliation.find_or_create_by_name a
      next if @member.affiliations.include? affiliation
      @member.affiliations << affiliation
    end

    parse_skill_list(params[:skills]).each do |s|
      skill = Skill.find_or_create_by_name(s)
      next if @member.skills.include? skill
      @member.skills << skill
    end

    @member.save!
    redirect_to members_path
  end

  def toggle_ambassador
    m = Member.find(params[:id])
    m.ambassador = !m.ambassador?
    m.save!
    redirect_to member_path(m.id)
  end

  def toggle_admin
    m = Member.find(params[:id])
    m.admin = !m.admin?
    m.save!
    redirect_to member_path(m.id)
  end

private

  def approved_member?
    redirect_to root_path unless current_member.approved?
  end

  def parse_affiliation_list affiliations
    affiliations ||= ''
    affiliations.split(/\s*,\s*/)
  end

  def parse_skill_list skills
    skills ||= ''
    skills.split(/\s*,\s*/)
  end

end

app/helpers/members_helper.rb
module MembersHelper

  def comma_list_of_affiliations_for member
    return if member.affiliations.nil?
    member.affiliations.collect(&:name).join(', ')
  end

  def comma_list_of_skills_for member
    return if member.skills.nil?
    member.skills.collect(&:name).join(', ')
  end

  def affiliations_list_for member
    return if member.affiliations.nil?
    links = member.affiliations.map do |a|
      %Q{<a href="/members?q[affiliations_name_cont]=#{a.name}" class="affiliation" data-search="#{a.name}">#{a.name}</a>}
    end
    raw links.join(', ')
  end

  def skills_list_for member
    return if member.skills.nil?
    links = member.skills.map do |s|
      %Q{<a href="/members?q[skills_name_cont]=#{s.name}" class="skills" data-search="#{s.name}">#{s.name}</a>}
    end
    raw links.join(', ')
  end

  def toggle_ambassador_button id
    if current_member.admin?
      button_to('Toggle Ambassador Status', toggle_ambassador_member_path(id), method: 'put', class: 'btn btn-primary')
    end
  end

  def toggle_admin_button id
    if current_member.admin?
      button_to('Toggle Admin Status', toggle_admin_member_path(id), method: 'put', class: 'btn btn-primary')
    end
  end

end

app/views/members/_list.html.haml
%table.table.table-striped
  %thead
    %tr
      %th Name
      %th Affiliations
      %th Skills
      %th Ambassadorness
      %th Email
  %tbody
    - @members.each do |member|
      %tr
        %td= link_to member.name, member_path(member)
        %td= affiliations_list_for(member)
        %td= skills_list_for(member)
        %td
          - if member.ambassador?
            .icon-user
        %td= member.email

app/views/members/_member_list.html.haml
%table.table.table-striped
  %thead
    %tr
      %th Name
      %th Affiliations
      %th Skills
      %th Ambassadorness
      %th Email
  %tbody
    - @members.each do |member|
      %tr
        %td= link_to member.name, member_path(member)
        %td= affiliations_list_for(member)
        %td= skills_list_for(member)
        %td= image_tag 'dolphin.jpg' if member.ambassador?
        %td= member.email

app/views/members/_search.html.haml
%p Find members with:
= search_form_for @q do |f|
  .row
    .span3
      .control-group
        = f.label 'Affiliation like:',  class: 'control-label'
      .controls
        = f.text_field :affiliations_name_cont, class: 'text_field'
    .span3
      .control-group
        = f.label 'Skill like:', class: 'control-label'
      .controls
        = f.text_field :skills_name_cont, class: 'text_field'
    .span6
      .span2
        .control-group
          = f.label 'Ambassadors only?', class: 'control-label'
      .span1
        .controls
          = check_box_tag :ambassador, '0', params[:ambassador] == '0', class: 'check_box'
  .form-actions
    = f.submit nil, class: 'btn btn-primary'

app/views/members/approve.html.haml
Approved new member #{@member.name}

app/views/members/edit.html.haml
- model_class = @member.class
%h1=t '.title', :default => t('helpers.titles.edit', :model => model_class.model_name.human, :default => "Edit #{model_class.model_name.human}")

= form_for @member, :html => { class: 'form-horizontal' } do |f|
  .control-group
    = label_tag :name, nil, class: 'control-label'
    .controls
      = text_field_tag :name, @member.name, class: 'text-field'
  .control-group
    = label_tag :affiliations, nil, class: 'control-label'
    .controls
      = text_field_tag :affiliations, affiliations_list_for(@member), class: 'text-field'
  .control-group
    = label_tag :skills, nil, class: 'control-label'
    .controls
      = text_field_tag :skills, skills_list_for(@member), class: 'text-field'
  .form-actions
    = f.submit nil, class: 'btn btn-primary'
    .btn= link_to t('.cancel', :default => t("helpers.links.cancel")), members_path

app/views/members/edit_profile.html.haml
- model_class = @member.class
%h1=t '.title', :default => t('helpers.titles.edit', :model => model_class.model_name.human, :default => "Edit #{model_class.model_name.human}")

= form_for @member, :html => { class: 'form-horizontal' } do |f|
  .control-group
    = label_tag :name, nil, class: 'control-label'
    .controls
      = text_field_tag :name, @member.name, class: 'text-field'
  .control-group
    = label_tag :affiliations, nil, class: 'control-label'
    .controls
      = text_field_tag :affiliations, comma_list_of_affiliations_for(@member), class: 'text-field'
  .control-group
    = label_tag :skills, nil, class: 'control-label'
    .controls
      = text_field_tag :skills, comma_list_of_skills_for(@member), class: 'text-field'
  .form-actions
    = f.submit nil, class: 'btn btn-primary'
    .btn= link_to t('.cancel', :default => t("helpers.links.cancel")), members_path

app/views/members/index.html.haml
- model_class = Member.new.class
%h1=t '.title', :default => model_class.model_name.human.pluralize

=render 'search'

=render 'list'

app/views/members/pending.html.haml
- model_class = Member.new.class
%h1=t '.pending-title', :default => 'Pending ' + model_class.model_name.human.pluralize
%table.table.table-striped
  %thead
    %tr
      %th= model_class.human_attribute_name(:name)
      %th= model_class.human_attribute_name(:email)
      %th= model_class.human_attribute_name(:whyhacker)
      %th=t '.actions', :default => t("helpers.actions")
  %tbody
    - @members.each do |member|
      %tr
        %td= link_to member.name, member_path(member)
        %td= member.email
        %td= member.whyhacker
        %td= button_to t('.approve', :default => t("helpers.links.approve")), approve_member_path(member), :method => 'put', class: 'btn btn-mini'

app/views/members/show.html.haml
- model_class = @member.class
%h1=t '.title', :default => model_class.model_name.human

.span12
  .row
    %strong= model_class.human_attribute_name(:name) + ':'
    = @member.name || "This user has not entered their name yet."
  .row
    %strong= model_class.human_attribute_name(:email) + ':'
    = @member.email
  .row
    %strong= model_class.human_attribute_name(:affiliations) + ':'
    = comma_list_of_affiliations_for(@member) || "This user has no affiliations yet."
  .row
    %strong= model_class.human_attribute_name(:skills) + ':'
    = comma_list_of_skills_for(@member) || "This user has no skills yet."

  .row
    %strong= model_class.human_attribute_name(:ambassador) + ':'
    -if @member.ambassador?
      #ambassador{style: "margin-right: 10px;", class: 'icon-user'}
    =toggle_ambassador_button(@member.id)
  .row
    %strong= model_class.human_attribute_name(:admin) + ':'
    -if @member.admin?
      #admin{style: "margin-right: 10px;", class: 'icon-eye-open'}
    =toggle_admin_button(@member.id)